---
- name: test
  hosts: all
  vars:
    - var1: var1test
    - var2: var2test
  tasks:
    - name: echo vars
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ var1 }}"
        - "{{ var2 }}"
